### ISSUE TITLE
Distribute libcif with Julia's artifacts system

### ISSUE THREAD

**Issue by Guillawme** [jamesrhester/CrystalInfoFramework.jl#7]
Hello,

For systems that don't provide cifapi/libcif in their default package manager, it could be helpful to distribute it through Julia's [artifacts](https://pkgdocs.julialang.org/v1/artifacts/) system. Its license allows redistribution.

**Comment by jamesrhester** [comment]
`libcif` requires both unicode libraries and sqlite libraries, so it is not as lightweight as it looks. Note that `CrystalInfoFramework` should be fully functional without `libcif` and the speed difference is less than it used to be, so an alternative plan might be to remove `libcif` completely.

**Comment by Guillawme** [comment]
Ah, ok. I thought the difference was still relevant because using the native parser emits a warning. And I had not thought about the whole dependency chain, which indeed complicates things quite a bit.

**Comment by jamesrhester** [comment]
Should the native parser become the default, then there is no reason to emit a warning if it uses the Julia parser instead of the C parser.

**Comment by jamesrhester** [comment]
Commit e59b52034171b8c7e0b8b43144c690dce03e7647 adds libcif support via `cif_api_jll`. It doesn't work for Windows, seems to be a problem with detecting end of file. Other platforms now do not need separate installation of cif_api.
